feat: inject secrets via module hook
getoutreach/stencil-golang pull request #525
Opened 2024-07-16 22:06 UTC by george-e-shaw-iv

* adds the ability to inject vault secrets via a module hook

2024-07-17 20:52 UTC, george-e-shaw-iv commented on templates/deployments/appname/app.config.jsonnet.tpl
The changes in this file actually allow config mixins to work. They weren't possible before the additions of the `+` operator (idk what it is called in jsonnet).

2024-07-17 21:45 UTC, malept requested changes
The changes themselves seem fine. Once you've updated the test snapshots, can you add some docs to the [module hooks markdown file](https://github.com/getoutreach/stencil-golang/blob/v1.23.3/docs/module-hooks.md)?

2024-07-17 22:43 UTC, malept commented on docs/module-hooks.md
> +**File**: `_helpers.tpl`
suggestion: I think ultimately this should point to the jsonnet template.
```suggestion
**File**: `deployments/appname/app.jsonnet.tpl`
```

2024-07-17 22:43 UTC, malept commented on docs/module-hooks.md
> +**Type**: `string`
suggestion: list of strings?
```suggestion
**Type**: `[]string`
```

2024-07-17 22:43 UTC, malept commented on docs/module-hooks.md
> +Adds a vault secret to be pulled within the deployment manifests and created in kubernetes.
Nit:
```suggestion
Adds Vault secret paths to be pulled within the deployment manifests and created in Kubernetes.
```

2024-07-23 16:56 UTC, malept approved these changes

2024-07-23 17:25 UTC, merged